/* eslint-disable @next/next/no-before-interactive-script-outside-document */

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'

import type { LocaleCode } from 'my-locales'

import { Providers } from './providers'

import 'src/styles/global.css'

const inter = Inter({ subsets: ['latin'] })

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'uk' }]
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: LocaleCode }
}) {
  return (
    <html lang={params.lang}>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <Script src="/theme.js" strategy="beforeInteractive" />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
