import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Container } from '@nextui-org/react'

import type { LocaleCode, Translation } from 'locales'
import * as locales from 'locales'
import { USERNAME } from 'src/constants'

import { useTranslations } from 'next-intl'

const Home: NextPage = () => {
  const t = useTranslations()

  return (
    <Container>
      <Head>
        <title>{USERNAME}</title>
        <meta property="og:title" content={USERNAME} key="title" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Hi, my name is <strong>{t('name')}</strong>
        </h1>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => ({
  props: {
    messages: locales[locale as LocaleCode] as Translation,
  },
})
